export const FILTER_NUM_COMMUTERS = 'data/FILTER_NUM_COMMUTERS'
export const HOVER_ROUTE_CHOICE = 'data/HOVER_ROUTE_CHOICE'
export const REQUEST_ZONE_JOURNEYS = 'data/REQUEST_ZONE_JOURNEYS'
export const RECEIVE_ZONE_JOURNEYS = 'data/RECEIVE_ZONE_JOURNEYS'
